source "https://api.berkshelf.com"

metadata

# Testing dependencies
cookbook "java", "= 1.22.0"
cookbook "minitest-handler", "= 0.2.1"
cookbook "test_flume_consumer", "= 1.0", path: "../test_flume_consumer"