name               "test_flume_consumer"
maintainer         "Joshua Hyde"
maintainer_email   "jrh3k5@gmail.com"
license            "Apache 2.0"
description        "A cookbook used to test the flume_agent cookbook"
long_description   "An example cookbook"
version            "1.0"
